### ISSUE TITLE
Pytorch复现精度不及预期

### ISSUE THREAD

**Issue by GuoRunTang** [travishsu/ReConPatch-TF#4]
请问您在使用ReConPatch的过程中，它的精度是否有和论文描述一致，我尝试了很多参数感觉表现不及预期，精度有在下降

**Comment by kimsax** [comment]
> 请问您在使用ReConPatch的过程中，它的精度是否有和论文描述一致，我尝试了很多参数感觉表现不及预期，精度有在下降

请问可以分享一下您的pytorch复现代码吗 他的结果大概和论文差多少
